FROM python:3.14

RUN apt-get update -y && \
    apt-get install -y python3-dev gcc && \
    apt-get install -y firefox-esr && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN wget 'https://github.com/mozilla/geckodriver/releases/download/v0.37.1/geckodriver-v0.37.1-linux-aarch64.tar.gz' && \
    tar xf geckodriver*.tar.gz && \
    rm geckodriver*.tar.gz
