name: Build images and push to docker hub

on: workflow_dispatch

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out the code'
        uses: actions/checkout@v6
      - run: ./build.sh
      - run: docker -u karenc -p ${{ secrets.DOCKER_HUB_RW_TOKEN }}
      - run: ./push.sh
